{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "vagaspcd",
    "description" : "",
    "version" : "0.1.0"
  },
  "servers" : [ {
    "url" : "https://virtserver.swaggerhub.com/milena-rosa/vagaspcd/0.1.0",
    "description" : "SwaggerHub API Auto Mocking"
  } ],
  "paths" : { },
  "components" : { }
}